In [1]:
import numpy as np

In [2]:
cd ..

/home/gautam/Desktop/python


In [3]:
from mcts.agents import RandomAgent, HumanAgent, MCTSAgent
from mcts.tictactoe import TicTacToeEnv
from mcts.connectfour import ConnectFourEnv

## Testing

In [4]:
def run_episode(agents, env, render=False):
    """Run agents on env and return total rewards."""
    env.reset()
    if render:
        env.render()
    total_reward = np.zeros(len(agents))
    while not env.done:
        action = agents[env.turn].act(env)
        _, rewards, _, _ = env.step(action)
        total_reward += rewards
        if render:
            env.render()
    return total_reward

In [5]:
env = ConnectFourEnv()
agents = [MCTSAgent(timeout=.1), MCTSAgent(timeout=.1)]

In [ ]:
%time returns = np.array([run_episode(agents, env) for _ in range(10)])

In [ ]:
"""(returns == 1).sum(axis=0)"""
returns

In [6]:
env = ConnectFourEnv()
agents = [HumanAgent(), MCTSAgent(timeout=0.1)]

In [7]:
run_episode(agents, env, render=True)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Input action: 3
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0 -1  1  0  0  0]]
Input action: 3
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0 -1  1  0  0  0]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0 -1  1  0  0  0]]
Input action: 2
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0 -1  1  0  0  0]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0 -1 -1  0  0  0]
 [ 0  0  1  1  0  0  0]
 [ 0  0 -1  1  0  0  0]]
Input action: 4
[[ 0 

array([-1.,  1.])

In [9]:
agents[1].root.visits

558