In [1]:
import numpy as np

In [2]:
cd ..

/Users/dylanpeifer/Documents/programs/MCTS-TicTacToe


In [3]:
from mcts.agents import RandomAgent, HumanAgent, MCTSAgent
from mcts.tictactoe import TicTacToeEnv
from mcts.connectfour import ConnectFourEnv

## Testing

In [4]:
def run_episode(agents, env, render=False):
    """Run agents on env and return total rewards."""
    env.reset()
    if render:
        env.render()
    total_reward = np.zeros(len(agents))
    while not env.done:
        action = agents[env.turn].act(env)
        _, rewards, _, _ = env.step(action)
        total_reward += rewards
        if render:
            env.render()
    return total_reward

In [5]:
env = TicTacToeEnv()
agents = [RandomAgent(), MCTSAgent(timeout=.1)]

In [6]:
%time returns = np.array([run_episode(agents, env) for _ in range(100)])

CPU times: user 33.4 s, sys: 304 ms, total: 33.7 s
Wall time: 33.6 s


In [7]:
(returns == 1).sum(axis=0)

array([ 4, 85])

In [8]:
env = TicTacToeEnv()
agents = [HumanAgent(), MCTSAgent(timeout=1.0)]

In [9]:
run_episode(agents, env, render=True)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Input action: (1, 1)
[[0 0 0]
 [0 1 0]
 [0 0 0]]
[[ 0  0  0]
 [ 0  1  0]
 [-1  0  0]]
Input action: (0, 2)
[[ 0  0  1]
 [ 0  1  0]
 [-1  0  0]]
[[ 0  0  1]
 [ 0  1  0]
 [-1  0 -1]]
Input action: (2, 1)
[[ 0  0  1]
 [ 0  1  0]
 [-1  1 -1]]
[[ 0 -1  1]
 [ 0  1  0]
 [-1  1 -1]]
Input action: (0, 0)
[[ 1 -1  1]
 [ 0  1  0]
 [-1  1 -1]]
[[ 1 -1  1]
 [-1  1  0]
 [-1  1 -1]]
Input action: (1, 2)
[[ 1 -1  1]
 [-1  1  1]
 [-1  1 -1]]


array([0., 0.])