In [1]:
import numpy as np

In [2]:
cd ..

/home/gautam/Desktop/python


In [3]:
from mcts.agents import RandomAgent, HumanAgent, MCTSAgent
from mcts.tictactoe import TicTacToeEnv
from mcts.connectfour import ConnectFourEnv

In [ ]:
from mcts.connectfour import ConnectFourApp, GraphicInterface, TextInterface
app = ConnectFourApp(GraphicInterface())
app.run()


## Testing

In [4]:
def run_episode(agents, env, render=False):
    """Run agents on env and return total rewards."""
    env.reset()
    if render:
        env.render()
    total_reward = np.zeros(len(agents))
    while not env.done:
        action = agents[env.turn].act(env)
        _, rewards, _, _ = env.step(action)
        total_reward += rewards
        if render:
            env.render()
    return total_reward

In [5]:
env = ConnectFourEnv()
agents = [MCTSAgent(timeout=0.1), MCTSAgent(timeout=0.1)]

In [6]:
%time returns = np.array([run_episode(agents, env) for _ in range(10)])

CPU times: user 21.7 s, sys: 147 ms, total: 21.9 s
Wall time: 21.7 s


In [7]:
"""(returns == 1).sum(axis=0)"""
returns

array([[ 1., -1.],
       [ 1., -1.],
       [-1.,  1.],
       [-1.,  1.],
       [ 1., -1.],
       [ 1., -1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [ 1., -1.]])

In [8]:
env = ConnectFourEnv()
agents = [HumanAgent(),MCTSAgent(timeout=2)]

In [9]:
run_episode(agents, env, render=True)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Input action: 3
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0 -1  0  0  0]
 [ 0  0  0  1  0  0  0]]
Input action: 3
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0 -1  0  0  0]
 [ 0  0  0  1  0  0  0]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0 -1  0  0  0]
 [ 0  0  0  1 -1  0  0]]
Input action: 4
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0]
 [ 0  0  0 -1  1  0  0]
 [ 0  0  0  1 -1  0  0]]
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0]
 [ 0  0  0 -1  1  0  0]
 [ 0  0  0  1 -1  0  0]]
Input action: 5
[[ 0 

array([ 1., -1.])

In [ ]:
env = ConnectFourEnv()
agents = [MCTSAgent(timeout=.1),RandomAgent(),]
[run_episode(agents, env) for _ in range(100)]